# http://travis-ci.org/#!/gjhiggins/FuXi
language: python
sudo: false
# whitelist
branches:
  only:
    - master

python:
    - 2.7

env:
    - TOX_ENV=flake
    - TOX_ENV=docs
    - TOX_ENV=cover
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=pypy

before_install:
    - pip install -U setuptools pip  # seems travis comes with a too old setuptools for html5lib
    - bash .travis.getOWLtestsuite.sh

install:
    - pip install nose
    - pip install tox

script:
    tox -e $TOX_ENV

after_success:
    - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi

notifications:
    email: false
