# http://travis-ci.org/#!/gjhiggins/FuXi
language: python
sudo: false
# whitelist
branches:
  only:
    - master

python:
    - 2.7

env:
    - TOX_ENV=pyflakes
    - TOX_ENV=docs
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy

install:
    - pip install tox

before_script:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then flake8 --exclude=tools,examples --exit-zero FuXi; fi

script:
    tox -e $TOX_ENV

after_success:
    - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi

notifications:
    email: false
